language: go

go:
  - 1.6

sudo: required

cache: false

go_import_path: snaproute/src/l3

before_install:
  - mkdir -p $HOME/gopath/src/reltools
  - mkdir -p $HOME/gopath/src/external/src
  - mkdir -p $HOME/gopath/src/generated/src
  - export GOPATH=$GOPATH:$HOME/gopath/src/snaproute:$HOME/gopath/src/external:$HOME/gopath/src/generated

install:
  - sudo apt-get install python-dev python-bitarray python-paramiko python-netaddr
  - ls -al $HOME/gopath/src/snaproute/src
  - git clone git@github.com:SnapRoute/apps.git $HOME/gopath/src/snaproute/src/apps
  - git clone git@github.com:SnapRoute/asicd.git $HOME/gopath/src/snaproute/src/asicd
  - git clone git@github.com:SnapRoute/config.git $HOME/gopath/src/snaproute/src/config
  - git clone git@github.com:SnapRoute/docs.git $HOME/gopath/src/snaproute/src/docs
  - git clone git@github.com:SnapRoute/flexSdk.git $HOME/gopath/src/snaproute/src/flexSdk
  - git clone git@github.com:SnapRoute/infra.git $HOME/gopath/src/snaproute/src/infra
  - git clone git@github.com:SnapRoute/l2.git $HOME/gopath/src/snaproute/src/l2
  - git clone git@github.com:SnapRoute/models.git $HOME/gopath/src/snaproute/src/models
  - git clone git@github.com:SnapRoute/utils.git $HOME/gopath/src/snaproute/src/utils
  - git clone git@github.com:SnapRoute/reltools.git $HOME/gopath/src/reltools
  - git clone git@github.com:SnapRoute/pyang.git $HOME/gopath/src/external/src/pyang
  - git clone git@github.com:SnapRoute/openconfig.git $HOME/gopath/src/external/src/openconfig

before_script:
  - ln -s $HOME/gopath/src/reltools/Makefile $HOME/gopath/src/snaproute/src/Makefile
  - export SR_CODE_BASE=$HOME/gopath/src
  - cd $HOME/gopath/src/snaproute/src;make buildinfogen;make codegen

script:
  - go test ./...
